name: bundle-source-code

on:
  workflow_call:
    inputs:
      tag:
        description: "FFmpeg Version"
        required: true
        type: string

jobs:
  bundle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout FFmpeg
        uses: actions/checkout@v4
        with:
          repository: FFmpeg/FFmpeg
          ref: n${{ inputs.tag }}
          path: FFmpeg

      - name: Set source archive name
        working-directory: FFmpeg
        run: |
          source_short_sha="$(git rev-parse --short HEAD)"
          echo "SOURCE_ARCHIVE=FFmpeg-${{ inputs.tag || github.event.inputs.tag }}-${source_short_sha}-source-code.tar.xz" >> "$GITHUB_ENV"

      - name: Copy license file
        working-directory: FFmpeg
        run: |
          mkdir -p dist
          cp COPYING.LGPLv2.1 dist/LICENSE

      - name: Archive source code
        working-directory: FFmpeg
        run: |
          archive_path="$RUNNER_TEMP/${SOURCE_ARCHIVE}"
          XZ_OPT='-9e' tar -cJf "$archive_path" --exclude='./.git' --exclude='./doc' --exclude='./tests' .
          mv "$archive_path" "dist/${SOURCE_ARCHIVE}"

      - name: Upload source code archive artifact
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.SOURCE_ARCHIVE }}
          path: FFmpeg/dist/${{ env.SOURCE_ARCHIVE }}
          tag_name: v${{ inputs.tag }}
          archive: false

      - name: Upload source code license artifact
        uses: softprops/action-gh-release@v2
        with:
          name: LICENSE
          path: FFmpeg/dist/LICENSE
          tag_name: v${{ inputs.tag }}
          archive: false
