name: draft-release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "FFmpeg Version"
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ inputs.tag }}
          draft: true
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
