name: macos-arm64

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'FFmpeg Version Tag'
        required: true
        type: string

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout FFmpeg
        uses: actions/checkout@v4
        with:
          repository: FFmpeg/FFmpeg
          ref: ${{ inputs.tag }}

      - name: configure
        run: ./configure

      - name: build
        run: make
